### ISSUE TITLE
Add support for bitbucket and gitlab in purl2url to get download URLs

### ISSUE THREAD

**Issue by TG1999** [package-url/packageurl-python#124]

**Comment by tdruez** [comment]
@TG1999 We support the following PURLs in `purl2url.get_download_url`

- `pkg:gitlab/hoppr/hoppr@v1.11.1-dev.2` -> https://gitlab.com/hoppr/hoppr/-/archive/v1.11.1-dev.2/hoppr-v1.11.1-dev.2.tar.gz
- `pkg:bitbucket/robeden/trove@3.0.3` -> https://bitbucket.org/robeden/trove/get/3.0.3.tar.gz

See https://github.com/package-url/packageurl-python/blob/main/tests/contrib/test_purl2url.py#L84 and https://github.com/package-url/packageurl-python/blob/main/tests/contrib/test_purl2url.py#L80

Let me know if we are missing something else, you can close otherwise ;)
