### ISSUE TITLE
Unavailable URLs returned by purl2url on GitHub PURLs

### ISSUE THREAD

**Issue by tdruez** [package-url/packageurl-python#42]
```
>>> from packageurl.contrib import purl2url
>>> purl2url.purl2url('pkg:github/package-url/packageurl-python@0.9.1')
'https://github.com/package-url/packageurl-python/tree/0.9.1'
```

The returned URL https://github.com/package-url/packageurl-python/tree/0.9.1 leads to a 404.
The proper URL is actually https://github.com/package-url/packageurl-python/tree/v0.9.1 with the "v" prefix.

Note that the "v" prefix in a tag name is a convention and optional.

**Comment by scovetta** [comment]
Hi @tdruez I think the issue here is that the "version" for GitHub is taken to mean a tag, so your purl should actually contain the "v" prefix here, specifically because the packageurl-python project uses "v" as a prefix for tags.

```python
>>> purl2url.purl2url('pkg:github/package-url/packageurl-python@v0.9.1')
'https://github.com/package-url/packageurl-python/tree/v0.9.1'
```

Other projects, like Python-Pillow, use just the raw version number, so this works as expected:

```python
>>> purl2url.purl2url('pkg:github/python-pillow/Pillow@7.2.0')
'https://github.com/python-pillow/pillow/tree/7.2.0'
```

**Comment by tdruez** [comment]
The version prefix is now kept as a `version_prefix` qualifier in `url2purl`. This allows to generate valid URLs in `purl2url`.
We choose this approach instead of keeping the prefix in the @ version for maximum compatibility across existing PURLs.
